/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Home
 */
public class TelaPrincipalMDI extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipalMDI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        itSair = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenu();
        itCadastrar = new javax.swing.JMenuItem();
        itAlterar = new javax.swing.JMenuItem();
        itExcluir = new javax.swing.JMenuItem();
        itPesquisar = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenu();
        itCadastrar2 = new javax.swing.JMenuItem();
        itAlterar2 = new javax.swing.JMenuItem();
        itExcluir2 = new javax.swing.JMenuItem();
        itPesquisar2 = new javax.swing.JMenuItem();
        mnSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        mnArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        mnArquivo.setText("Arquivo");

        itSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door_out.png"))); // NOI18N
        itSair.setText("Sair");
        mnArquivo.add(itSair);

        MenuPrincipal.add(mnArquivo);

        mnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        mnUsuarios.setText("Usuarios");

        itCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N
        itCadastrar.setText("Cadastrar");
        itCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCadastrarActionPerformed(evt);
            }
        });
        mnUsuarios.add(itCadastrar);

        itAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_edit.png"))); // NOI18N
        itAlterar.setText("Alterar");
        mnUsuarios.add(itAlterar);

        itExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_delete.png"))); // NOI18N
        itExcluir.setText("Excluir");
        mnUsuarios.add(itExcluir);

        itPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zoom.png"))); // NOI18N
        itPesquisar.setText("Pesquisar");
        mnUsuarios.add(itPesquisar);

        MenuPrincipal.add(mnUsuarios);

        mnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        mnClientes.setText("Clientes");

        itCadastrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_add.png"))); // NOI18N
        itCadastrar2.setText("Cadastrar");
        mnClientes.add(itCadastrar2);

        itAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_edit.png"))); // NOI18N
        itAlterar2.setText("Alterar");
        mnClientes.add(itAlterar2);

        itExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group_delete.png"))); // NOI18N
        itExcluir2.setText("Excluir");
        mnClientes.add(itExcluir2);

        itPesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zoom.png"))); // NOI18N
        itPesquisar2.setText("Pesquisar");
        mnClientes.add(itPesquisar2);

        MenuPrincipal.add(mnClientes);

        mnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/information.png"))); // NOI18N
        mnSobre.setText("Sobre");
        MenuPrincipal.add(mnSobre);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCadastrarActionPerformed
        CadastrarUsuario regUser = new CadastrarUsuario();
        jDesktopPane1.add(regUser);
        regUser.setVisible(true);
        
    }//GEN-LAST:event_itCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem itAlterar;
    private javax.swing.JMenuItem itAlterar2;
    private javax.swing.JMenuItem itCadastrar;
    private javax.swing.JMenuItem itCadastrar2;
    private javax.swing.JMenuItem itExcluir;
    private javax.swing.JMenuItem itExcluir2;
    private javax.swing.JMenuItem itPesquisar;
    private javax.swing.JMenuItem itPesquisar2;
    private javax.swing.JMenuItem itSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenu mnUsuarios;
    // End of variables declaration//GEN-END:variables

}
